### ISSUE TITLE
Self-lock out - Reset the database

### ISSUE THREAD

**Issue by Gymnae** [alexandregz/twofactor_gauthenticator#42]
Somehow I managed to lock myself out months ago and have thus deactivated the plugin.
Since then, whenever I re-activate the plugin it asks for the code, which I supply, but seems to be wrong as it returns to the normal login screen with the message that i successfully logged out.
Is there anyway to reset the plugin and it's database to a clean slate and begin again with a new two factor code?
I would love to use the plugin again.

Cheers,
Peter

**Comment by alexandregz** [comment]
Hi:

If you have access to the DB, just convert to NULL the field `roundcubemail`.`users`.`preferences` (for your user) to restart all plugin configs.

Regards.

**Comment by anothatuber** [comment]
For documentation reasons since I needed a solution after losing my phone with the generator:
If you lose the generator and have direct DB access (example is for mysql):
```
$ mysql
> use roundcubemail
> select * from users;
```
And there you are, in the field preferences, field "secret". I just entered it manually in my generator and was able to log in into roundcube again.
