### ISSUE TITLE
Not working with Elastic skin

### ISSUE THREAD

**Issue by OpenAai** [alexandregz/twofactor_gauthenticator#92]
As the title says. I have been testing with the latest Git version, 1.4 (beta?), on Ubuntu 16.04 with Apache 2.4

**Comment by adam12b1** [comment]
+1 on getting it working with the upcoming Roundcube Elastic skin, please! Currently it's a bit busted, most noticeably in that the Show QR Code feature fails - you can't see the code itself because, I guess, the plugin's table formatting doesn't play well with the new dynamic widgety user interface.

**Comment by SURYASWAROOP** [comment]
the logical functionality working fine but the UI in the new Elastic Skin was not properly aligned
and in the new theme if i click the show qrcode its unable to load the ajax properly please fix the UI bug asap, thank you
![image](https://user-images.githubusercontent.com/7898495/44958998-b28bbe00-af05-11e8-9fa5-5cc4d24a3d09.png)

**Comment by alexandregz** [comment]
For use with elastic skin, you can use "elastic_skin" branch [https://github.com/alexandregz/twofactor_gauthenticator/tree/elastic_skin](https://github.com/alexandregz/twofactor_gauthenticator/tree/elastic_skin) :

$ git clone https://github.com/alexandregz/twofactor_gauthenticator
$ git checkout elastic_skin

(or use @oxycoder repo directly)

From RC blog: "Because we don’t yet consider the Elastic theme fully complete, it’s not set to be the default theme." [https://roundcube.net/news/2019/02/28/roundcube-1.4-rc1-released](https://roundcube.net/news/2019/02/28/roundcube-1.4-rc1-released)

**Comment by OpenAai** [comment]
I have just tested it with `git pull ; git checkout elastic_skin` on my RC1 installation, but I see no change.
